version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_USER: ${DB.USER}
      POSTGRES_PASSWORD: ${DB.PASSWORD}
      POSTGRES_DB: ${DB.NAME}
    ports: 
      - ${DB.PORT}:5432