CREATE TABLE summoners (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    puuid TEXT NOT NULL UNIQUE,
    account_id TEXT NOT NULL,
    profile_icon_id INTEGER NOT NULL,
    revision_date BIGINT NOT NULL,
    name TEXT NOT NULL,
    r_summoner_id TEXT NOT NULL,
    summoner_level BIGINT NOT NULL,
    region VARCHAR(4) NOT NULL
);

CREATE TABLE summoner_rankeds (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    summoner_id BIGINT NOT NULL UNIQUE,
    s_tier TEXT NOT NULL,
    f_tier TEXT NOT NULL,
    s_rank TEXT NOT NULL,
    f_rank TEXT NOT NULL,
    s_league_points INT NOT NULL,
    f_league_points INT NOT NULL,
    s_wins INT NOT NULL,
    f_wins INT NOT NULL,
    s_losses INT NOT NULL,
    f_losses INT NOT NULL,
    s_hot_streak BOOLEAN NOT NULL,
    f_hot_streak BOOLEAN NOT NULL,
    s_veteran BOOLEAN NOT NULL,
    f_veteran BOOLEAN NOT NULL,
    s_fresh_blood BOOLEAN NOT NULL,
    f_fresh_blood BOOLEAN NOT NULL,
    s_inactive BOOLEAN NOT NULL,
    f_inactive BOOLEAN NOT NULL,
    s_is_ms BOOLEAN NOT NULL,
    f_is_ms BOOLEAN NOT NULL,
    s_ms_w INT NOT NULL,
    f_ms_w INT NOT NULL,
    s_ms_l INT NOT NULL,
    f_ms_l INT NOT NULL,
    s_ms_prg TEXT NOT NULL,
    f_ms_prg TEXT NOT NULL,
    s_ms_trg INT NOT NULL,
    f_ms_trg INT NOT NULL
)